In [34]:
# Import modules
from __future__ import print_function

%matplotlib inline
%load_ext autoreload
%autoreload 2

import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [38]:
from utils.layer_funcs import conv2d_forward

# Set test parameters.
x_shape = (2, 5, 5, 3) #(batch, height, width, channels)
w_shape = (3, 3, 3, 5) #(filter_height, filter_width, channels, num_of_filt)

channels = w_shape[-1]

x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
w = np.linspace(-0.2, 0.3, num=np.prod(w_shape)).reshape(w_shape)
b = np.linspace(-0.1, 0.2, num=channels)
pad = 1
stride = 2
your_feedforward = conv2d_forward(x, w, b, pad, stride)

print("Your feedforward result (size :{}) is: ".format(your_feedforward.shape))
print(your_feedforward)

Your feedforward result (size :(2, 3, 3, 5)) is: 
[[[[-0.17767004 -0.10534459 -0.03301913  0.03930632  0.11163177]
   [-0.14008665 -0.0678814   0.00432385  0.0765291   0.14873435]
   [-0.09471101 -0.0207628   0.05318542  0.12713363  0.20108184]]

  [[ 0.06484073  0.14191425  0.21898778  0.2960613   0.37313483]
   [ 0.1523525   0.23228839  0.31222428  0.39216017  0.47209606]
   [ 0.04323099  0.12273866  0.20224632  0.28175398  0.36126164]]

  [[-0.08652509 -0.00608585  0.0743534   0.15479265  0.23523189]
   [-0.14941751 -0.06504157  0.01933437  0.10371031  0.18808625]
   [-0.19829711 -0.1162351  -0.03417309  0.04788891  0.12995092]]]


 [[[ 0.38218171  0.46803015  0.55387859  0.63972704  0.72557548]
   [ 0.54755735  0.64004708  0.73253681  0.82502655  0.91751628]
   [ 0.2622959   0.3497671   0.43723831  0.52470951  0.61218071]]

  [[ 0.44821747  0.54557548  0.64293349  0.7402915   0.8376495 ]
   [ 0.49921717  0.60957979  0.7199424   0.83030502  0.94066763]
   [ 0.12234048  0.22213263  0

In [39]:
from utils.layer_funcs import conv2d_backward
# Set test parameters. Please don't change it.
np.random.seed(234)
d_top = np.random.normal(size=your_feedforward.shape)
your_dw, your_db, d_w_shape = conv2d_backward(d_top, x, w, b, pad, stride)

print("Your weights' gradients result (size :{}) is: ".format(d_w_shape))
print(your_dw)
print("Your biases' gradients result is: ")
print(your_db)

Your weights' gradients result (size :(3, 3, 3, 5)) is: 
[[[[-1.5313261  -0.70268556  0.29999267  0.45013902  0.02658925]
   [-1.54455043 -0.70704637  0.30712039  0.44705678  0.03977736]
   [-1.55777476 -0.71140718  0.31424811  0.44397453  0.05296546]]

  [[-1.26240393  0.57156177  0.10980501  0.66016111  0.86998156]
   [-1.26837463  0.58999709  0.11420201  0.66061212  0.88652154]
   [-1.27434533  0.60843241  0.11859902  0.66106313  0.90306152]]

  [[-0.51455235  0.97098958  0.25403568  0.30196443  1.63905567]
   [-0.51641576  0.991624    0.25206962  0.29911685  1.66167077]
   [-0.51827917  1.01225842  0.25010356  0.29626927  1.68428587]]]


 [[[-1.33339813 -0.50007572  0.83947043  0.15420289  0.19049381]
   [-1.36002174 -0.50099608  0.85300835  0.15279624  0.20119824]
   [-1.38664535 -0.50191643  0.86654628  0.1513896   0.21190267]]

  [[-0.92133176  1.09775008  0.67767936  0.23495075  1.52139887]
   [-0.93428666  1.11277168  0.69159827  0.2388919   1.54379329]
   [-0.94724155  1.1277

In [6]:
from utils.layer_funcs import max_pool_forward

# Set test parameters.
x_shape = (2, 5, 5, 3) #(batch, height, width, channels)
x = np.linspace(-0.5, 0.5, num=np.prod(x_shape)).reshape(x_shape)
pool_size = 2
stride = 2

your_feedforward = max_pool_forward(x, pool_size, stride)

print("Your feedforward result (size :{}) is: ".format(your_feedforward.shape))
print(your_feedforward)

X_tf = tf.placeholder(tf.float32, shape=x_shape)

init_op = tf.global_variables_initializer()
feedforward = tf.nn.max_pool(X_tf, [1, pool_size, pool_size, 1], [1, stride, stride, 1], padding='VALID')
with tf.Session() as sess:
     tf_feedforward = sess.run(feedforward, feed_dict={X_tf: x})

## Print validation result
print("Is your feedforward correct? {}".format(np.allclose(your_feedforward, tf_feedforward)))

Your feedforward result (size :(2, 2, 2, 3)) is: 
[[[[-0.37919463 -0.37248322 -0.36577181]
   [-0.33892617 -0.33221477 -0.32550336]]

  [[-0.17785235 -0.17114094 -0.16442953]
   [-0.13758389 -0.13087248 -0.12416107]]]


 [[[ 0.12416107  0.13087248  0.13758389]
   [ 0.16442953  0.17114094  0.17785235]]

  [[ 0.32550336  0.33221477  0.33892617]
   [ 0.36577181  0.37248322  0.37919463]]]]
Is your feedforward correct? True


In [ ]:
from utils.layer_funcs import max_pool_backward

# Set test parameters.
np.random.seed(234)
dout = np.random.normal(size=your_feedforward.shape)
dx = max_pool_backward(dout, x, pool_size, stride)

print("Your inputs' gradients result (size :{}) is: ".format(dx.shape))
print(dx)


### Load Data

In [7]:
# Load the raw Fashion Mnist data.
img_cols = 28
img_rows = 28
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Train data: 59000 samples from original train set: 1~59000
# Validation data: 1000 samples from original train set: 59000~60000
num_training = 59000
num_validation = 1000

X_train = X_train.reshape(-1, img_rows, img_cols, 1)
X_test = X_test.reshape(-1, img_rows, img_cols, 1)
X_val = X_train[num_training:num_training+num_validation, :]
y_val = y_train[num_training:num_training+num_validation]
X_train = X_train[0:num_training, :]
y_train = y_train[0:num_training]

mean_image = np.mean(X_train, axis=0).astype(np.float32)
X_train = X_train.astype(np.float32) - mean_image
X_val = X_val.astype(np.float32) - mean_image

print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Validation data shape: ', X_val.shape)
print('Validation labels shape: ', y_val.shape)

Training data shape:  (59000, 28, 28, 1)
Training labels shape:  (59000,)
Validation data shape:  (1000, 28, 28, 1)
Validation labels shape:  (1000,)


### CNN model

In [8]:
from utils.neuralnets.cnn.LeNet_model import training

tf.reset_default_graph()
training(X_train, y_train, X_val, y_val, 
         conv_featmap=[6],
         fc_units=[84],
         conv_kernel_size=[5],
         pooling_size=[2],
         l2_norm=0.01,
         seed=235,
         learning_rate=1e-4,
         epoch=20,
         batch_size=295,
         verbose=False,
         pre_trained_model=None)

Building example LeNet. Parameters: 
conv_featmap=[6]
fc_units=[84]
conv_kernel_size=[5]
pooling_size=[2]
l2_norm=0.01
seed=235
learning_rate=0.0001
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

number of batches for training: 200
Instructions for updating:
Use tf.cast instead.
epoch 1 
Best validation accuracy! iteration:100 accuracy: 65.1%
Best validation accuracy! iteration:200 accuracy: 69.5%
epoch 2 
Best validation accuracy! iteration:300 accuracy: 71.3%
Best validation accuracy! iteration:400 accuracy: 72.8%
epoch 3 
Best validation accuracy! iteration:500 accuracy: 73.9%
Best validation accuracy! iteration:600 accuracy: 74.3%
epoch 4 
Best validation accuracy! iteration:700 accuracy: 75.3%
Best validation accuracy! iteration:800 accuracy: 75.7%
epoch 5 
Best valida

### Show the model structure graph

In [10]:
# Show the graph
from utils.neuralnets.cnn.jupyter_tensorboard import show_graph 

tf.reset_default_graph()

with tf.Session() as sess:
    saver = tf.train.import_meta_graph('model/lenet_1572809175.meta')
    graph = tf.get_default_graph()
    show_graph(graph)

In [1]:
! pwd

/Users/DrewAfromsky/Desktop/Fall_2019/ECBM_4040-Neural_Networks_and_Deep_Learning/E4040_2019Fall_assignments/assignment_2


In [22]:
from utils.neuralnets.cnn.my_LeNet_model import my_training
tf.reset_default_graph()

my_training(X_train, y_train, X_val, y_val, 
         conv_featmap=[6],
         fc_units=[84],
         conv_kernel_size=[5],
         pooling_size=[2],
         l2_norm=0.01,
         seed=235,
         learning_rate=1e-3,
         epoch=20,
         batch_size=250,
         verbose=False,
         pre_trained_model=None)

Building  MyLeNet. Parameters: 
conv_featmap=[6]
fc_units=[84]
conv_kernel_size=[5]
pooling_size=[2]
l2_norm=0.01
seed=235
learning_rate=0.001
number of batches for training: 236
epoch 1 
Best validation accuracy! iteration:100 accuracy: 71.5%
Best validation accuracy! iteration:200 accuracy: 77.3%
epoch 2 
Best validation accuracy! iteration:300 accuracy: 81.1%
Best validation accuracy! iteration:400 accuracy: 83.9%
epoch 3 
Best validation accuracy! iteration:500 accuracy: 86.3%
Best validation accuracy! iteration:600 accuracy: 86.8%
Best validation accuracy! iteration:700 accuracy: 87.4%
epoch 4 
Best validation accuracy! iteration:800 accuracy: 87.8%
Best validation accuracy! iteration:900 accuracy: 89.5%
epoch 5 
epoch 6 
Best validation accuracy! iteration:1200 accuracy: 89.7%
epoch 7 
epoch 8 
Best validation accuracy! iteration:1800 accuracy: 90.7%
epoch 9 
epoch 10 
epoch 11 
Best validation accuracy! iteration:2400 accuracy: 91.0%
epoch 12 
epoch 13 
epoch 14 
epoch 15 
Best 

![Tensorboard_2](./utils/notebook_images/png.png)

In [25]:
# Show the graph
from utils.neuralnets.cnn.jupyter_tensorboard import show_graph 
tf.reset_default_graph()

with tf.Session() as sess:
    saver = tf.train.import_meta_graph('model/lenet_1572813796.meta')
    graph = tf.get_default_graph()
    show_graph(graph)

In [27]:
# Show the graph
from utils.neuralnets.cnn.jupyter_tensorboard import show_graph 

tf.reset_default_graph()

with tf.Session() as sess:
    saver = tf.train.import_meta_graph('model/lenet_1572813796.meta')
    graph = tf.get_default_graph()
    show_graph(graph)